title: My Jekyll Site
description: A simple Jekyll website with a Hero Section

# Enable Markdown parsing and allow HTML
markdown: kramdown
theme: minima  # Use a Jekyll theme or remove this if using custom styles


